apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
nameSuffix: -redis
labels:
  - pairs: {opspilot.io/target: redis}
    includeSelectors: true
patches:
  - path: target.yaml
