apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
nameSuffix: -user-service
labels:
  - pairs: {opspilot.io/target: user-service}
    includeSelectors: true
patches:
  - path: target.yaml
